obj-$(CONFIG_FB_INGENIC_X1000)	+= fb_v10/
obj-$(CONFIG_FB_INGENIC_X2000)	+= fb_v11/
obj-$(CONFIG_FB_INGENIC_V12) += fb_v12/
obj-$(CONFIG_VFB_JZ) +=jz_vfb/
obj-$(CONFIG_SPI_FB_V12) += spi_fb_v12/
obj-$(CONFIG_FB_INGENIC_STAGE) += fb_stage/
